from ludic.catalog.headers import H1, H2, H3, H4, Anchor
from ludic.catalog.items import Key, Pairs, Value
from ludic.catalog.lists import Item, List, NumberedList
from ludic.catalog.typography import Code, CodeBlock, Link, Paragraph
from ludic.web import Request

from web.pages import Page


def typography(request: Request) -> Page:
    return Page(
        H1("Typography"),
        Paragraph(
            f"The module {Code("ludic.catalog.typography")} contains the following "
            "components:"
        ),
        H4("Link"),
        Paragraph(
            f"This text contains a {Link(
                "link", to=str(request.url_for("catalog:index")))}.",
        ),
        CodeBlock(
            """
            from ludic.catalog.typography import Link

            Link("link", to="https://getludic.dev")  # appends target="_blank"
            Link("link", to="/")                     # does not append target="_blank"
            """,
            language="python",
        ),
        H4("Paragraph"),
        Paragraph("Here is some text wrapped in a paragraph."),
        CodeBlock(
            """
            from ludic.catalog.typography import Paragraph

            Paragraph("Here is some text wrapped in a paragraph.")
            """,
            language="python",
        ),
        H4("Code"),
        Paragraph(f"This text contains code: {Code("let mut x = 0;")}"),
        CodeBlock(
            """
            from ludic.catalog.typography import Code

            Code("let mut x = 0;")
            """,
            language="python",
        ),
        H4("Code Block"),
        Paragraph(
            "The following block contains a Rust code with syntax highlighting "
            "generated by Pygments:"
        ),
        CodeBlock(
            """
            fn main() {
                println!("Hello, world!");
            }
            """,
            language="rust",
        ),
        CodeBlock(
            """
            from ludic.catalog.typography import CodeBlock

            CodeBlock(
                \"\"\"
                fn main() {
                    println!("Hello, world!");
                }
                \"\"\",
                language="rust"
            )
            """,
            language="python",
        ),
        H4("Pairs"),
        CodeBlock(
            """
            from ludic.catalog.items import Pair, Key, Value

            Pairs(
                Key("First Name:"),
                Value("John"),
                Key("Last Name:"),
                Value("Doe"),
            )
            """,
            language="python",
        ),
        Pairs(
            Key("First Name:"),
            Value("John"),
            Key("Last Name:"),
            Value("Doe"),
        ),
        H4("List"),
        CodeBlock(
            """
            from ludic.catalog.lists import List, Item

            List(
                Item("A"),
                Item("B"),
                Item("C"),
            )
            """,
            language="Python",
        ),
        List(
            Item("A"),
            Item("B"),
            Item("C"),
        ),
        H4("Numbered List"),
        CodeBlock(
            """
            from ludic.catalog.lists import NumberedList, Item

            NumberedList(
                Item("One"),
                Item("Two"),
                Item("Three"),
            )
            """,
            language="Python",
        ),
        NumberedList(
            Item("One"),
            Item("Two"),
            Item("Three"),
        ),
        H2("Headers"),
        Paragraph(
            f"The module {Code("ludic.catalog.headers")} contains components "
            "rendering as HTML headers (h1-h4)."
        ),
        H1("H1", anchor=False),
        H2("H2", anchor=False),
        H3("H3", anchor=False),
        H4("H4", anchor=False),
        CodeBlock(
            """
            from ludic.catalog.headers import H1, H2, H3, H4

            H1("H1")
            H2("H2")
            H3("H3")
            H4("H4")
            """,
            language="python",
        ),
        Paragraph(
            f"The module also contains the {Code("Anchor")} component, which can be "
            "used to create an anchor link next to the header."
        ),
        H4("H4 With Anchor", anchor=Anchor("#", target="h4-with-anchor")),
        CodeBlock(
            """
            from ludic.catalog.headers import Anchor, H4

            H4("H4 With Anchor", anchor=Anchor("#", target="h4-with-anchor"))
            """,
            language="python",
        ),
        Paragraph(
            "It is possible to generate the anchor automatically using the "
            f"{Code("anchor=True")} attribute:"
        ),
        H3("H3 With Anchor", anchor=True),
        CodeBlock(
            """
            from ludic.catalog.headers import H3

            H3("H3 With Anchor", anchor=True)
            """,
            language="python",
        ),
        request=request,
        active_item="typography",
    )
